apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-petservices
  labels:
    app.kubernetes.io/part-of: micropets-app
    app.tanzu.vmware.com/workload-type: micropet-service-git
spec:  
  serviceAccountName: tap-default
  source:
    git:
      url: https://github.com/bmoussaud/micropets-app/
      ref:
        branch: master
  params:
    - name: port
      value: 8080
    - name: observability
      value: false    
